### ISSUE TITLE
unable to launch HiddenEye.py

### ISSUE THREAD

**Issue by asciiterminal** [DarkSecDevelopers/HiddenEye#403]
i have thoroughly looked through the program and i am unable to execute the program even by  using the following command `python HiddenEye.py`  and i happen to get this error code
`Traceback (most recent call last):
  File "HiddenEye.py", line 13, in <module>
    from Defs.Checks import *
  File "/root/HiddenEye/Defs/Checks.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request
`

**Comment by usama7628674** [comment]
@asciiterminal `pip3 install requests`

**Comment by usama7628674** [comment]
@asciiterminal `python3 HiddenEye.py`

**Comment by asciiterminal** [comment]
@usama7628674 i get error via using your instruction 
`Traceback (most recent call last):
  File "HiddenEye.py", line 13, in <module>
    from Defs.Checks import *
  File "/root/HiddenEye/Defs/Checks.py", line 7, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'
`

**Comment by aamirawan7584** [comment]
Make a virtual environment and install requirement.txt. it will install all
required module.

**Comment by asciiterminal** [comment]
@aamirawan7584 i did as you said but then i got this while executing `HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):
  File "./HiddenEye.py", line 15, in <module>
    from Defs.Actions import *
  File "/root/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/root/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'
`

**Comment by usama7628674** [comment]
@asciiterminal Run again

**Comment by aamirawan7584** [comment]
@asciiterminal  delete Setting.ini file from folder and run again.

**Comment by prince812** [comment]
root@root:~/Desktop/HiddenEye-master# python3 HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 9, in <module>
    import ssl
  File "/usr/local/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

**what's this error ? please help me.**

**Comment by Kavinesh20** [comment]
`HURRAY!! Internet is available.. We can Continue
Traceback (most recent call last):
  File "./HiddenEye.py", line 15, in <module>
    from Defs.Actions import *
  File "/home/parrot020/Desktop/Hackings/HiddenEye/Defs/Actions.py", line 28, in <module>
    colorTheme = colorSelector()
  File "/home/parrot020/Desktop/Hackings/HiddenEye/Defs/ThemesManager.py", line 24, in colorSelector
    if config.get("Defaults", "theme") == "anaglyph":
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Defaults'
` 

i got this error while i running the Hidden eye.......Please anyone give the solution.......:)

**Comment by asciiterminal** [comment]
fixed it had to update python to 3.8
using `apt-get install python3.8`

**Comment by aamirawan7584** [comment]
@Kavinesh20  please posting in thread ! kindly first read whole thread :(

**Comment by Zeptic1337** [comment]
anyone fixed this issue yet? I did everything everyone said and still getting the same error. Thank you

**Comment by aupsham** [comment]
> fixed it had to update python to 3.8
> using `apt-get install python3.8`

just do this your error will fix if still get
use apt-get install python3-wget

**Comment by Moltivie** [comment]
@usama7628674 proceed to close the issue.

**Comment by aadi-1111** [comment]
I got this error. What to do now?...

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/aditya1111/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/home/aditya1111/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by Nikhil-ls** [comment]
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by aadi-1111** [comment]
> Traceback (most recent call last):
> File "HiddenEye.py", line 8, in 
> import Defs.ActionManager.main_runner as main_runner
> File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in 
> from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
> File "/data/data/com.termux/files/home/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in 
> from pyngrok import ngrok
> ModuleNotFoundError: No module named 'pyngrok'

I got the answer for this.
First you have to download hiddeneye in root user. Then you have to download pip if you have not. The code is: sudo apt update then after this you have to sudo apt upgrade then sudo apt install python3-pip.
After this you have to go to your hiddeneye directory and do pip3 install -r requirements.txt
This will download the requirements of hiddeneye which is pyngrok and it will install it automatically and after this you have to do python3 HiddenEye.py
This will open HiddenEye successfully.

**Comment by Masticoza** [comment]
I get this error after all the peocess,  im a newbie pls help :cd HiddenEye
$ python HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/data/data/com.termux/files/home/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'
$

**Comment by Masticoza** [comment]
Pls im now getting this how do i accept?  WITH GREAT POWER - COMES GREAT RESPONSIBILITY
Do you accept license?
Enter: Yes, i do to confirm.

HiddenEye >>>  yes, i do
You are not allowed to use this app without accepting license.
$ y
No command y found, did you mean:
 Command [ in package coreutils
 Command k in package kona
 Command o in package o

**Comment by darkmidus** [comment]
@Masticoza enter it exactly: Yes, i do
