### ISSUE TITLE
Getting module attribute error while running

### ISSUE THREAD

**Issue by pksharma132** [DarkSecDevelopers/HiddenEye#622]
when i tried to run HiddenEye.py it showed these errors

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/pksharma/Documents/Hack/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/pksharma/Documents/Hack/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in <module>
    import Defs.ActionManager.Server.server_menu as server_menu
  File "/home/pksharma/Documents/Hack/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 11, in <module>
    import Defs.ActionManager.Server.server_runner as server_runner
  File "/home/pksharma/Documents/Hack/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 12, in <module>
    import Defs.ActionManager.Server.server_menu as server_menu
AttributeError: module 'Defs.ActionManager.Server' has no attribute 'server_menu'

I did every step correctly

**Comment by mousekali** [comment]
I have the same issue
when I use 'python3 HiddenEye.py' I get this 
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/kali/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/kali/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in <module>
    import Defs.ActionManager.Server.server_menu as server_menu
  File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_menu.py", line 11, in <module>
    import Defs.ActionManager.Server.server_runner as server_runner
  File "/home/kali/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 19, in <module>
    enter_server_www = chdir("Server/www")
FileNotFoundError: [Errno 2] No such file or directory: 'Server/www'

and when I use ./hiddeneye.py I get a different error
from: can't read /var/mail/os
./HiddenEye.py: line 8: import: command not found
./HiddenEye.py: line 9: import: command not found
./HiddenEye.py: line 10: import: command not found
./HiddenEye.py: line 11: import: command not found
./HiddenEye.py: line 12: import: command not found
./HiddenEye.py: line 13: import: command not found
./HiddenEye.py: line 14: import: command not found
./HiddenEye.py: line 15: import: command not found
./HiddenEye.py: line 16: import: command not found
./HiddenEye.py: line 17: import: command not found
./HiddenEye.py: line 21: syntax error near unexpected token `agreement'
./HiddenEye.py: line 21: `agreement = simple_informant.terms_of_service_message()'

**Comment by sTiKyt** [comment]
Should be fixed with https://github.com/DarkSecDevelopers/HiddenEye/commit/3696e54c9b8e0ef7ade9fb9c7e5eefd13b14251d

**Comment by sTiKyt** [comment]
You are free to re-open

**Comment by pksharma132** [comment]
Still getting the same error after running the updated code
![Screenshot from 2020-05-28 13 49 50](https://user-images.githubusercontent.com/55243875/83117217-6d9cb780-a0ea-11ea-9fc5-fff77bde0ff0.png)
